namespace Qx.Model.Wired;

internal static partial class WiredFormKnowledge
{
    private static IReadOnlyDictionary<(WiredFormCategory, int), WiredFormUsage> create_entries()
    {
        var result = new Dictionary<(WiredFormCategory, int), WiredFormUsage>();
        void add(WiredFormCategory category, params (int Code, string Purpose)[] rows)
        {
            foreach (var row in rows)
                result.Add((category, row.Code), usage(category, row.Code, row.Purpose));
        }

        add(WiredFormCategory.Trigger,
            (0, "Starts a stack when a user's chat matches the configured text rule."),
            (1, "Starts a stack when a user steps or sits on selected furniture."),
            (2, "Starts a stack when a user leaves selected furniture."),
            (3, "Starts a stack after the configured time since the Wired timer was reset."),
            (4, "Starts a stack when selected furniture is used to change its state."),
            (6, "Starts a stack repeatedly at a configured interval in half-second pulses."),
            (7, "Starts a stack when a matching user enters the room."),
            (8, "Starts a stack when a room game starts."),
            (9, "Starts a stack when a room game ends."),
            (10, "Starts a stack when a team reaches the configured game score."),
            (11, "Starts a stack when a compatible furniture movement produces a collision with a user."),
            (12, "Starts a stack repeatedly using the long-period timer settings."),
            (13, "Starts a stack when the selected bot reaches selected destination furniture."),
            (14, "Starts a stack when the selected bot reaches a user."),
            (15, "Starts a stack when a selected clock counter reaches the configured time."),
            (16, "Starts a stack when a user performs the configured action."),
            (17, "Starts a receiving stack when a signal arrives through the selected signal furniture."),
            (18, "Starts a stack when a user clicks selected furniture."),
            (19, "Starts a stack repeatedly using a short interval measured in milliseconds."),
            (20, "Starts a stack when the state of selected furniture changes."),
            (21, "Starts a stack when a user clicks a room tile."),
            (22, "Starts a stack when the selected variable changes in the configured way."),
            (23, "Starts a stack when a matching user leaves the room."),
            (24, "Starts a stack when one user clicks another user."),
            (25, "Starts a stack when a Wired transaction completes successfully."),
            (26, "Starts a stack when a Wired transaction fails."));

        add(WiredFormCategory.Action,
            (0, "Advances or reverses the state of selected furniture."),
            (1, "Resets the Wired timers used by elapsed-time triggers and conditions."),
            (3, "Restores the enabled state, position and direction components of a furniture snapshot."),
            (4, "Moves and rotates furniture using the configured movement choices."),
            (6, "Changes the score of the team associated with the selected user source."),
            (7, "Displays configured text with the selected audience and message style."),
            (8, "Teleports selected users to selected destination furniture."),
            (9, "Adds selected users to a game team."),
            (10, "Removes selected users from their game team."),
            (11, "Moves furniture toward the nearest user in the same row or column."),
            (12, "Moves furniture away from the nearest user in the same row or column."),
            (13, "Moves furniture in a direction and configures its response to a blocked move."),
            (14, "Changes the score of an explicitly selected game team."),
            (15, "Changes selected furniture to a random state."),
            (16, "Moves furniture using the form's configured destination controls."),
            (17, "Defines badge or product rewards and their distribution settings."),
            (18, "Executes selected Wired stacks directly, including the negative-action variant."),
            (19, "Kicks selected users from the room according to the configured criteria."),
            (20, "Mutes selected users for the configured duration."),
            (21, "Teleports a selected bot to destination furniture."),
            (22, "Makes a selected bot walk to destination furniture."),
            (23, "Makes a selected bot speak publicly."),
            (24, "Makes a selected bot give a configured hand item."),
            (25, "Starts or stops a selected bot following a user."),
            (26, "Changes the figure of a selected bot."),
            (27, "Makes a selected bot talk or whisper to selected users."),
            (28, "Starts, pauses or resets selected clock-counter furniture."),
            (29, "Sets the altitude of selected furniture."),
            (30, "Sends a signal and its selected user/furniture payload, including the negative-action variant."),
            (31, "Freezes selected users to restrict their movement."),
            (32, "Releases selected users from a Wired movement freeze."),
            (33, "Moves furniture by relative offsets."),
            (34, "Moves furniture relative to separate destination furniture."),
            (35, "Moves furniture toward selected users."),
            (38, "Adjusts the time of selected clock-counter furniture."),
            (39, "Assigns a variable to the selected holders with the configured initial value."),
            (40, "Removes a variable from selected holders."),
            (41, "Changes a variable value using the configured operation and operands."),
            (42, "Moves or rotates selected users."),
            (43, "Moves selected users toward destination furniture."),
            (44, "Teleports selected users to a configured room."),
            (45, "Requests a currency payout from a selected chest."),
            (46, "Requests a furniture payout from a selected chest."),
            (47, "Starts a Wired transaction using the selected contract configuration."),
            (48, "Cancels the relevant Wired transaction."),
            (49, "Writes a Wired log entry, including the negative-action variant."),
            (51, "Configures progress toward an achievement."),
            (52, "Applies the configured avatar effect."),
            (53, "Configures a height override and its mode; the field definition does not establish a unit."),
            (54, "Changes click-through behavior for selected users or furniture."),
            (55, "Places temporary furniture using the configured placement controls."),
            (56, "Removes temporary furniture selected by the effect."),
            (57, "Moves a selection of furniture together as a group."),
            (58, "Configures progress on a reward track."),
            (59, "Resets reward-track progress using the configured reset options."));

        add(WiredFormCategory.Condition,
            (0, "Compares selected furniture with the enabled components of a saved snapshot."),
            (1, "Checks whether selected furniture has users on it."),
            (2, "Checks whether selected users are on selected furniture."),
            (3, "Checks whether more than the configured time has passed since timer reset."),
            (4, "Checks whether less than the configured time has passed since timer reset."),
            (5, "Checks whether the room's user count is within the configured limits."),
            (6, "Checks selected users' game-team membership."),
            (7, "Checks whether selected furniture has other furniture on top."),
            (8, "Compares furniture identities or types between two configured sources."),
            (10, "Checks whether selected users belong to the room's group."),
            (11, "Checks whether selected users wear the configured badge."),
            (12, "Checks whether selected users wear the configured avatar effect."),
            (14, "Checks that selected furniture has no users on it."),
            (18, "Checks that selected furniture has no other furniture on top."),
            (24, "Checks whether the configured date range is active."),
            (25, "Checks whether selected users hold the configured hand item."),
            (26, "Compares user identities or types between configured sources."),
            (28, "Compares the current time with the configured time rule."),
            (29, "Compares the current date with the configured date rule."),
            (31, "Checks the configured team's game ranking."),
            (32, "Checks whether selected users are performing the configured action."),
            (34, "Compares a game team's score with the configured score rule."),
            (35, "Compares selected clock counters with the configured time rule."),
            (36, "Checks the altitude of selected furniture."),
            (37, "Checks the direction selected users face."),
            (38, "Checks the number of entities supplied by a configured input source."),
            (39, "Checks whether the configured movement can be performed."),
            (40, "Checks whether selected holders have the chosen variable."),
            (42, "Compares variable values using the configured operands and comparison."),
            (43, "Compares the age of a variable against the configured rule."),
            (44, "Checks a user's level against the configured rule."),
            (45, "Checks how many items a selected chest contains."),
            (46, "Checks whether selected chests contain specified furniture types."));

        add(WiredFormCategory.Selector,
            (0, "Selects furniture matching configured furniture types."),
            (1, "Adds explicitly picked furniture to the furniture selection."),
            (2, "Selects users by entity type."),
            (3, "Selects users in the configured game team."),
            (4, "Selects furniture stacked on reference furniture."),
            (5, "Selects furniture carried by the current signal."),
            (6, "Selects furniture in a tile-offset neighborhood around a reference entity."),
            (7, "Selects furniture inside a room rectangle."),
            (8, "Selects users standing or sitting on reference furniture."),
            (9, "Selects users performing the configured action."),
            (10, "Selects users carried by the current signal."),
            (11, "Selects users whose names match the configured list."),
            (12, "Selects users in a tile-offset neighborhood around a reference entity."),
            (13, "Selects users inside a room rectangle."),
            (14, "Selects users holding the configured hand item."),
            (15, "Selects users matching the configured group selection."),
            (16, "Selects furniture matching an altitude rule."),
            (17, "Selects furniture according to a variable rule."),
            (18, "Selects users according to a variable rule."),
            (19, "Combines remote selections using union or intersection."));

        add(WiredFormCategory.Addon,
            (0, "Changes how conditions are combined or how many must pass."),
            (1, "Chooses one random effect from the stack."),
            (2, "Chooses one previously unused effect from the stack."),
            (5, "Limits stack executions within a configured time window."),
            (6, "Disables movement animation for compatible effects."),
            (7, "Changes movement physics, including height and collision inputs."),
            (8, "Configures carrying users along with moving furniture."),
            (9, "Sets the animation duration for compatible movement effects."),
            (10, "Limits or samples an existing furniture selection."),
            (11, "Limits or samples an existing user selection."),
            (12, "Filters a furniture selection using variable values."),
            (13, "Filters a user selection using variable values."),
            (14, "Substitutes a user name into an output-text placeholder."),
            (15, "Substitutes a variable value into an output-text placeholder."),
            (16, "Captures text from a configured input marker into a variable."),
            (17, "Configures ordered execution of effects in the stack."),
            (18, "Scans selected chests for configured furniture types."),
            (19, "Substitutes a furniture name into an output-text placeholder."),
            (20, "Builds dynamic contract elements from configured values and sources."),
            (21, "Configures projectile movement and direction behavior."),
            (22, "Configures the curved or jumping path of compatible movement."),
            (1000, "Maps numeric variable values to configured text outputs."),
            (1001, "Derives levels and progress information from an experience variable."),
            (1002, "Derives time-related outputs from a variable."),
            (1200, "Displays a user or furniture variable as a health indicator."),
            (1201, "Displays a user or furniture variable as a progress bar."),
            (1202, "Displays level and progress information for a user or furniture variable."),
            (1203, "Displays a user or furniture variable with a selected status style."),
            (1204, "Displays a user or furniture variable as a boss health bar."),
            (1205, "Displays a user or furniture variable as a styled number."),
            (2000, "Configures a global text placeholder."),
            (2001, "Configures achievement-related variable behavior."),
            (2002, "Configures Web API access to supported variables."));

        add(WiredFormCategory.Variable,
            (0, "Defines a variable whose holders are furniture items."),
            (1, "Defines a variable whose holders are users."),
            (2, "Defines a room/global variable shared within its configured scope."),
            (3, "Defines a variable associated with a Wired execution context."),
            (4, "References an available shared variable from another room."),
            (5, "Defines the configured quest variable and progress settings."),
            (6, "Defines a chain of quest-variable stages."),
            (7, "Defines an echo variable using the configured source reference."),
            (8, "Defines the configured daily-task variable."));

        return result;
    }
}
