namespace Qx.Model.Wired;

/// <summary>A named choice for an integer form field.</summary>
/// <param name="Name">The stable option name.</param>
/// <param name="Value">The wire value.</param>
public sealed record WiredFormChoice(string Name, int Value);

/// <summary>Machine-readable named choices for typed form controls.</summary>
public static class WiredFormChoices
{
    private static readonly IReadOnlyList<WiredFormChoice> choices_0 = Array.AsReadOnly<WiredFormChoice>([new("ContainsKeyword", 0), new("ExactMatch", 1), new("AllText", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_1 = Array.AsReadOnly<WiredFormChoice>([new("Any", 0), new("Red", 1), new("Green", 2), new("Blue", 3), new("Yellow", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_2 = Array.AsReadOnly<WiredFormChoice>([new("Wave", 0), new("Blow", 1), new("Laugh", 2), new("Respect", 3), new("Awake", 4), new("Sleep", 5), new("Sit", 6), new("Stand", 7), new("Lay", 8), new("Sign", 10), new("Dance", 11), new("Action67", 67)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_3 = Array.AsReadOnly<WiredFormChoice>([new("AllStates", 0), new("CurrentState", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_4 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("Increased", 1), new("Decreased", 2), new("Unchanged", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_5 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("ThisRoom", 1), new("AnotherRoom", 2), new("Inspection", 4), new("External", 8), new("All", -1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_6 = Array.AsReadOnly<WiredFormChoice>([new("NextState", 0), new("PreviousState", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_7 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("UpperRight", 4), new("Right", 8), new("LowerRight", 5), new("Down", 9), new("LowerLeft", 6), new("Left", 10), new("UpperLeft", 7), new("Up", 11), new("EitherUpperLeftLowerRight", 2), new("EitherUpperRightLowerLeft", 3), new("Random", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_8 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("Clockwise", 1), new("Counterclockwise", 2), new("Random", 3)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_9 = Array.AsReadOnly<WiredFormChoice>([new("OnlyTheUser", 0), new("Everyone", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_10 = Array.AsReadOnly<WiredFormChoice>([new("UserPreference", -1), new("Wide", 0), new("Normal", 1), new("Thin", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_11 = Array.AsReadOnly<WiredFormChoice>([new("Red", 1), new("Green", 2), new("Blue", 3), new("Yellow", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_12 = Array.AsReadOnly<WiredFormChoice>([new("Wired", 0), new("BattleBanzai", 1), new("Freeze", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_13 = Array.AsReadOnly<WiredFormChoice>([new("UpperRight", 0), new("Right", 1), new("LowerRight", 2), new("Down", 3), new("LowerLeft", 4), new("Left", 5), new("UpperLeft", 6), new("Up", 7)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_14 = Array.AsReadOnly<WiredFormChoice>([new("Once", 0), new("EveryNDays", 1), new("EveryNHours", 2), new("EveryNMinutes", 3)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_15 = Array.AsReadOnly<WiredFormChoice>([new("Talk", 0), new("Shout", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_16 = Array.AsReadOnly<WiredFormChoice>([new("Stop", 0), new("Start", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_17 = Array.AsReadOnly<WiredFormChoice>([new("Talk", 0), new("Whisper", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_18 = Array.AsReadOnly<WiredFormChoice>([new("Start", 0), new("Stop", 1), new("Reset", 2), new("Pause", 3), new("Resume", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_19 = Array.AsReadOnly<WiredFormChoice>([new("Increase", 0), new("Decrease", 1), new("SetValue", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_20 = Array.AsReadOnly<WiredFormChoice>([new("Assign", 0), new("Add", 1), new("Subtract", 2), new("Multiply", 3), new("Divide", 4), new("Power", 5), new("Modulo", 6), new("Minimum", 40), new("Maximum", 41), new("RandomUpperBound", 50), new("Absolute", 60), new("And", 100), new("Or", 101), new("Xor", 102), new("Not", 103), new("LeftShift", 104), new("RightShift", 105), new("BitCount", 110)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_21 = Array.AsReadOnly<WiredFormChoice>([new("None", -1), new("UpperRight", 0), new("Right", 1), new("LowerRight", 2), new("Down", 3), new("LowerLeft", 4), new("Left", 5), new("UpperLeft", 6), new("Up", 7)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_22 = Array.AsReadOnly<WiredFormChoice>([new("None", -1), new("UpperRight", 0), new("Right", 1), new("LowerRight", 2), new("Down", 3), new("LowerLeft", 4), new("Left", 5), new("UpperLeft", 6), new("Up", 7), new("Clockwise", 9), new("Counterclockwise", 10)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_23 = Array.AsReadOnly<WiredFormChoice>([new("KeepWalkingIfMovedCloserToTarget", 0), new("KeepWalking", 1), new("StopWalking", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_24 = Array.AsReadOnly<WiredFormChoice>([new("SpecifiedAmount", 0), new("All", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_25 = Array.AsReadOnly<WiredFormChoice>([new("Random", 0), new("FirstInFirstOut", 1), new("LastInFirstOut", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_26 = Array.AsReadOnly<WiredFormChoice>([new("Normal", 0), new("Multiplier", 1), new("AutoMultiplier", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_27 = Array.AsReadOnly<WiredFormChoice>([new("SpecifiedContract", 0), new("AnyOngoingTransaction", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_28 = Array.AsReadOnly<WiredFormChoice>([new("SetProgress", 0), new("AddToExistingProgress", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_29 = Array.AsReadOnly<WiredFormChoice>([new("Default", 0), new("ClickUserButWalkBehind", 1), new("PassThroughUser", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_30 = Array.AsReadOnly<WiredFormChoice>([new("Default", 0), new("PassThroughFurniture", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_31 = Array.AsReadOnly<WiredFormChoice>([new("SourceLocation", 0), new("CustomLocation", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_32 = Array.AsReadOnly<WiredFormChoice>([new("OnTopOfTargetLocation", 0), new("SourceAltitude", 1), new("CustomAltitude", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_33 = Array.AsReadOnly<WiredFormChoice>([new("AnySelectedFurnitureHasAnAvatar", 0), new("AllSelectedFurnitureHaveAvatars", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_34 = Array.AsReadOnly<WiredFormChoice>([new("AnySelectedFurnitureHasNoAvatar", 1), new("AllSelectedFurnitureHaveNoAvatars", 0)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_35 = Array.AsReadOnly<WiredFormChoice>([new("AnyTeam", 0), new("Red", 1), new("Green", 2), new("Blue", 3), new("Yellow", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_36 = Array.AsReadOnly<WiredFormChoice>([new("AnySelectedFurnitureHasFurnitureOnIt", 0), new("AllSelectedFurnitureHaveFurnitureOnThem", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_37 = Array.AsReadOnly<WiredFormChoice>([new("OneOrMoreSelectedFurnitureHaveNoFurnitureOnThem", 0), new("AllSelectedFurnitureHaveNone", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_38 = Array.AsReadOnly<WiredFormChoice>([new("Habbo", 1), new("Pet", 2), new("Bot", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_39 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("Monday", 1), new("Tuesday", 2), new("Wednesday", 4), new("Thursday", 8), new("Friday", 16), new("Saturday", 32), new("Sunday", 64)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_40 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("January", 1), new("February", 2), new("March", 4), new("April", 8), new("May", 16), new("June", 32), new("July", 64), new("August", 128), new("September", 256), new("October", 512), new("November", 1024), new("December", 2048)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_41 = Array.AsReadOnly<WiredFormChoice>([new("TriggererTeam", 0), new("Red", 1), new("Green", 2), new("Blue", 3), new("Yellow", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_42 = Array.AsReadOnly<WiredFormChoice>([new("First", 0), new("Second", 1), new("Third", 2), new("Fourth", 3)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_43 = Array.AsReadOnly<WiredFormChoice>([new("LessThan", 0), new("Equal", 1), new("GreaterThan", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_44 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("UpperRight", 1), new("Right", 2), new("LowerRight", 4), new("Down", 8), new("LowerLeft", 16), new("Left", 32), new("UpperLeft", 64), new("Up", 128)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_45 = Array.AsReadOnly<WiredFormChoice>([new("LessThan", 0), new("Equal", 1), new("GreaterThan", 2), new("LessThanOrEqual", 3), new("NotEqual", 4), new("GreaterThanOrEqual", 5)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_46 = Array.AsReadOnly<WiredFormChoice>([new("LowerThan", 0), new("HigherThan", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_47 = Array.AsReadOnly<WiredFormChoice>([new("CreationTime", 0), new("LastUpdateTime", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_48 = Array.AsReadOnly<WiredFormChoice>([new("Milliseconds", 0), new("Seconds", 1), new("Minutes", 2), new("Hours", 3), new("Days", 4), new("Weeks", 5), new("Months", 6), new("Years", 7)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_49 = Array.AsReadOnly<WiredFormChoice>([new("Above", 0), new("Below", 1), new("SameHeight", 2), new("AllFurnitureOnTile", 3)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_50 = Array.AsReadOnly<WiredFormChoice>([new("LowerThan", 0), new("Equals", 1), new("HigherThan", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_51 = Array.AsReadOnly<WiredFormChoice>([new("VariablePresenceOnly", 0), new("ConstantComparison", 1), new("VariableComparison", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_52 = Array.AsReadOnly<WiredFormChoice>([new("Union", 0), new("Intersection", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_53 = Array.AsReadOnly<WiredFormChoice>([new("All", 0), new("AtLeastOne", 1), new("NotAll", 2), new("None", 3), new("NumericComparison", -1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_54 = Array.AsReadOnly<WiredFormChoice>([new("LessThan", 0), new("Exactly", 1), new("MoreThan", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_55 = Array.AsReadOnly<WiredFormChoice>([new("StandingDirectlyOnMovingFurniture", 0), new("StandingOnSameTile", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_56 = Array.AsReadOnly<WiredFormChoice>([new("HighestValue", 0), new("LowestValue", 1), new("OldestCreation", 2), new("LatestCreation", 3), new("OldestUpdate", 4), new("LatestUpdate", 5)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_57 = Array.AsReadOnly<WiredFormChoice>([new("AllItemsInChest", 0), new("OnlyPreviewedItems", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_58 = Array.AsReadOnly<WiredFormChoice>([new("Credits", 0), new("Furniture", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_59 = Array.AsReadOnly<WiredFormChoice>([new("EightDirectionsStraight", 0), new("EightDirectionsDiffuse", 1), new("FourDirectionsOption1", 2), new("FourDirectionsOption2", 3)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_60 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("TilesTravelled", 1), new("UserCollisions", 2), new("FurnitureCollisions", 4), new("PositionX", 8), new("PositionY", 16), new("Altitude", 32), new("IsTravelling", 64)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_61 = Array.AsReadOnly<WiredFormChoice>([new("NormalStartToTarget", 0), new("OvershootXTiles", 1), new("AlwaysShootXTiles", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_62 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("CurrentLevel", 1), new("CurrentXp", 2), new("Progress", 4), new("ProgressPercentage", 8), new("XpRequired", 16), new("XpRemaining", 32), new("IsMaxed", 64), new("MaxLevel", 128)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_63 = Array.AsReadOnly<WiredFormChoice>([new("ManualInterpolation", 0), new("Linear", 1), new("Exponential", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_64 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("MillisecondsOfSecond", 2), new("SecondsOfMinute", 4), new("MinuteOfHour", 8), new("HourOfDay", 16), new("DayOfWeek", 32), new("DayOfMonth", 64), new("DayOfYear", 128), new("WeekOfYear", 256), new("MonthOfYear", 512), new("Year", 1024), new("Millisecond", 1048576), new("Second", 2097152), new("Minute", 4194304), new("Hour", 8388608), new("Day", 16777216), new("Week", 33554432), new("Month", 67108864)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_65 = Array.AsReadOnly<WiredFormChoice>([new("Value", 0), new("CreationTime", 1), new("LastUpdateTime", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_66 = Array.AsReadOnly<WiredFormChoice>([new("OnlyTheUser", 0), new("SameGameTeam", 1), new("Everyone", 2), new("UsersWithVariable", 3), new("UsersWithVariableEqualToSelectedValue", 4)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_67 = Array.AsReadOnly<WiredFormChoice>([new("Always", 0), new("WhenVariableUpdates", 1), new("OnMouseHover", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_68 = Array.AsReadOnly<WiredFormChoice>([new("None", 0), new("Created", 1), new("Increased", 2), new("Decreased", 4), new("Unchanged", 8)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_69 = Array.AsReadOnly<WiredFormChoice>([new("Left", 0), new("Right", 1), new("BothSides", 2)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_70 = Array.AsReadOnly<WiredFormChoice>([new("FixedValue", 0), new("ReferenceFromAnotherRoom", 1)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_71 = Array.AsReadOnly<WiredFormChoice>([new("WhileRoomActive", 1), new("Permanent", 10)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_72 = Array.AsReadOnly<WiredFormChoice>([new("WhileUserInRoom", 0), new("Permanent", 10), new("PermanentSharedAcrossRooms", 11)]);
    private static readonly IReadOnlyList<WiredFormChoice> choices_73 = Array.AsReadOnly<WiredFormChoice>([new("WhileRoomActive", 1), new("Permanent", 10), new("PermanentSharedAcrossRooms", 11)]);

    /// <summary>Gets named choices for a field; empty means no finite verified option set.</summary>
    /// <param name="definition">The form definition.</param>
    /// <param name="field">The stable field name.</param>
    /// <returns>The immutable choices.</returns>
    public static IReadOnlyList<WiredFormChoice> Get(WiredFormDefinition definition, string field) =>
        (definition.Category, definition.Code, field) switch
        {
            (WiredFormCategory.Trigger, 0, "match_mode") => choices_0,
            (WiredFormCategory.Trigger, 10, "team") => choices_1,
            (WiredFormCategory.Trigger, 16, "action") => choices_2,
            (WiredFormCategory.Trigger, 20, "state_mode") => choices_3,
            (WiredFormCategory.Trigger, 22, "change_mask") => choices_4,
            (WiredFormCategory.Trigger, 22, "origin_mask") => choices_5,
            (WiredFormCategory.Action, 0, "toggle_type") => choices_6,
            (WiredFormCategory.Action, 4, "movement") => choices_7,
            (WiredFormCategory.Action, 4, "rotation") => choices_8,
            (WiredFormCategory.Action, 7, "visibility") => choices_9,
            (WiredFormCategory.Action, 7, "bubble_width") => choices_10,
            (WiredFormCategory.Action, 9, "team") => choices_11,
            (WiredFormCategory.Action, 9, "game_type") => choices_12,
            (WiredFormCategory.Action, 13, "direction") => choices_13,
            (WiredFormCategory.Action, 14, "team") => choices_11,
            (WiredFormCategory.Action, 17, "interval_type") => choices_14,
            (WiredFormCategory.Action, 23, "chat_mode") => choices_15,
            (WiredFormCategory.Action, 23, "bubble_width") => choices_10,
            (WiredFormCategory.Action, 25, "following") => choices_16,
            (WiredFormCategory.Action, 27, "chat_mode") => choices_17,
            (WiredFormCategory.Action, 27, "bubble_width") => choices_10,
            (WiredFormCategory.Action, 28, "clock_control") => choices_18,
            (WiredFormCategory.Action, 29, "operation") => choices_19,
            (WiredFormCategory.Action, 38, "operation") => choices_19,
            (WiredFormCategory.Action, 41, "operation") => choices_20,
            (WiredFormCategory.Action, 42, "movement") => choices_21,
            (WiredFormCategory.Action, 42, "rotation") => choices_22,
            (WiredFormCategory.Action, 43, "walking_mode") => choices_23,
            (WiredFormCategory.Action, 45, "rewarding_mode") => choices_24,
            (WiredFormCategory.Action, 46, "rewarding_mode") => choices_24,
            (WiredFormCategory.Action, 46, "iteration_mode") => choices_25,
            (WiredFormCategory.Action, 47, "transaction_mode") => choices_26,
            (WiredFormCategory.Action, 48, "match_criteria") => choices_27,
            (WiredFormCategory.Action, 51, "progression_mode") => choices_28,
            (WiredFormCategory.Action, 54, "user_click") => choices_29,
            (WiredFormCategory.Action, 54, "furniture_click") => choices_30,
            (WiredFormCategory.Action, 55, "location_mode") => choices_31,
            (WiredFormCategory.Action, 55, "altitude_mode") => choices_32,
            (WiredFormCategory.Condition, 1, "require_all") => choices_33,
            (WiredFormCategory.Condition, 14, "require_any_without_avatar") => choices_34,
            (WiredFormCategory.Condition, 6, "team") => choices_35,
            (WiredFormCategory.Condition, 7, "require_all") => choices_36,
            (WiredFormCategory.Condition, 18, "require_all") => choices_37,
            (WiredFormCategory.Condition, 26, "user_type") => choices_38,
            (WiredFormCategory.Condition, 29, "weekday_mask") => choices_39,
            (WiredFormCategory.Condition, 29, "month_mask") => choices_40,
            (WiredFormCategory.Condition, 31, "team") => choices_41,
            (WiredFormCategory.Condition, 31, "placement") => choices_42,
            (WiredFormCategory.Condition, 32, "action") => choices_2,
            (WiredFormCategory.Condition, 34, "team") => choices_41,
            (WiredFormCategory.Condition, 34, "comparison") => choices_43,
            (WiredFormCategory.Condition, 35, "comparison") => choices_43,
            (WiredFormCategory.Condition, 36, "comparison") => choices_43,
            (WiredFormCategory.Condition, 37, "direction_mask") => choices_44,
            (WiredFormCategory.Condition, 38, "comparison") => choices_43,
            (WiredFormCategory.Condition, 42, "comparison") => choices_45,
            (WiredFormCategory.Condition, 43, "comparison") => choices_46,
            (WiredFormCategory.Condition, 43, "age_kind") => choices_47,
            (WiredFormCategory.Condition, 43, "duration_unit") => choices_48,
            (WiredFormCategory.Condition, 44, "comparison") => choices_43,
            (WiredFormCategory.Condition, 45, "comparison") => choices_45,
            (WiredFormCategory.Condition, 46, "comparison") => choices_45,
            (WiredFormCategory.Selector, 2, "user_type") => choices_38,
            (WiredFormCategory.Selector, 3, "team") => choices_35,
            (WiredFormCategory.Selector, 4, "relation") => choices_49,
            (WiredFormCategory.Selector, 9, "action") => choices_2,
            (WiredFormCategory.Selector, 16, "comparison") => choices_50,
            (WiredFormCategory.Selector, 17, "comparison") => choices_45,
            (WiredFormCategory.Selector, 17, "value_filter") => choices_51,
            (WiredFormCategory.Selector, 18, "comparison") => choices_45,
            (WiredFormCategory.Selector, 18, "value_filter") => choices_51,
            (WiredFormCategory.Selector, 19, "set_operation") => choices_52,
            (WiredFormCategory.Addon, 0, "mode") => choices_53,
            (WiredFormCategory.Addon, 0, "comparison") => choices_54,
            (WiredFormCategory.Addon, 8, "carry_mode") => choices_55,
            (WiredFormCategory.Addon, 12, "sort_order") => choices_56,
            (WiredFormCategory.Addon, 13, "sort_order") => choices_56,
            (WiredFormCategory.Addon, 18, "scanning_mode") => choices_57,
            (WiredFormCategory.Addon, 20, "payment_type") => choices_58,
            (WiredFormCategory.Addon, 20, "reward_type") => choices_58,
            (WiredFormCategory.Addon, 21, "direction_system") => choices_59,
            (WiredFormCategory.Addon, 21, "internal_variables") => choices_60,
            (WiredFormCategory.Addon, 21, "distance_mode") => choices_61,
            (WiredFormCategory.Addon, 1001, "subvariable_mask") => choices_62,
            (WiredFormCategory.Addon, 1001, "mode") => choices_63,
            (WiredFormCategory.Addon, 1002, "subvariable_mask") => choices_64,
            (WiredFormCategory.Addon, 1002, "time_source") => choices_65,
            (WiredFormCategory.Addon, 1200, "audience") => choices_66,
            (WiredFormCategory.Addon, 1200, "show_mode") => choices_67,
            (WiredFormCategory.Addon, 1200, "update_mask") => choices_68,
            (WiredFormCategory.Addon, 1201, "audience") => choices_66,
            (WiredFormCategory.Addon, 1201, "show_mode") => choices_67,
            (WiredFormCategory.Addon, 1201, "update_mask") => choices_68,
            (WiredFormCategory.Addon, 1202, "audience") => choices_66,
            (WiredFormCategory.Addon, 1202, "show_mode") => choices_67,
            (WiredFormCategory.Addon, 1202, "update_mask") => choices_68,
            (WiredFormCategory.Addon, 1203, "audience") => choices_66,
            (WiredFormCategory.Addon, 1203, "show_mode") => choices_67,
            (WiredFormCategory.Addon, 1203, "update_mask") => choices_68,
            (WiredFormCategory.Addon, 1204, "audience") => choices_66,
            (WiredFormCategory.Addon, 1204, "show_mode") => choices_67,
            (WiredFormCategory.Addon, 1204, "update_mask") => choices_68,
            (WiredFormCategory.Addon, 1205, "audience") => choices_66,
            (WiredFormCategory.Addon, 1205, "show_mode") => choices_67,
            (WiredFormCategory.Addon, 1205, "update_mask") => choices_68,
            (WiredFormCategory.Addon, 1205, "icon_alignment") => choices_69,
            (WiredFormCategory.Addon, 2000, "mode") => choices_70,
            (WiredFormCategory.Variable, 0, "availability") => choices_71,
            (WiredFormCategory.Variable, 1, "availability") => choices_72,
            (WiredFormCategory.Variable, 2, "availability") => choices_73,
            _ => []
        };

    /// <summary>Reports whether named choices can be combined as flags.</summary>
    /// <param name="definition">The form definition.</param>
    /// <param name="field">The stable field name.</param>
    /// <returns>Whether the option values are flags.</returns>
    public static bool IsFlags(WiredFormDefinition definition, string field) =>
        (definition.Category, definition.Code, field) switch
        {
            (WiredFormCategory.Trigger, 22, "change_mask") => true,
            (WiredFormCategory.Trigger, 22, "origin_mask") => true,
            (WiredFormCategory.Condition, 29, "weekday_mask") => true,
            (WiredFormCategory.Condition, 29, "month_mask") => true,
            (WiredFormCategory.Condition, 37, "direction_mask") => true,
            (WiredFormCategory.Addon, 21, "internal_variables") => true,
            (WiredFormCategory.Addon, 1001, "subvariable_mask") => true,
            (WiredFormCategory.Addon, 1002, "subvariable_mask") => true,
            (WiredFormCategory.Addon, 1200, "update_mask") => true,
            (WiredFormCategory.Addon, 1201, "update_mask") => true,
            (WiredFormCategory.Addon, 1202, "update_mask") => true,
            (WiredFormCategory.Addon, 1203, "update_mask") => true,
            (WiredFormCategory.Addon, 1204, "update_mask") => true,
            (WiredFormCategory.Addon, 1205, "update_mask") => true,
            _ => false
        };
}
