<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Qx.Headers.Flash</RootNamespace>
    <AssemblyName>QX.FlashHeaders</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flazzy\Flazzy.csproj" />
    <PackageReference Include="SharpCompress" Version="0.50.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="signatures.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="signatures.json" LogicalName="Qx.Headers.Flash.signatures.json" />
  </ItemGroup>

</Project>
