<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Qx.Desktop</RootNamespace>
    <AssemblyName>QX</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\qx.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\qx.ico" />
    <AvaloniaResource Include="Assets\Fonts\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="RoslynPad.Editor.Avalonia" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QX.Core\QX.Core.csproj" />
    <ProjectReference Include="..\QX.Presentation\QX.Presentation.csproj" />
    <ProjectReference Include="..\QX.Scripting\QX.Scripting.csproj" />
  </ItemGroup>

  <Target Name="ExcludeNativeSymbolsFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'" />
    </ItemGroup>
  </Target>

</Project>
