<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qx.ClientCatalog</RootNamespace>
    <AssemblyName>QX.ClientCatalog</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QX.ClientHeaders\QX.ClientHeaders.csproj" />
    <ProjectReference Include="..\QX.FlashHeaders\QX.FlashHeaders.csproj" />
    <ProjectReference Include="..\QX.Protocol\QX.Protocol.csproj" />
  </ItemGroup>

</Project>
