<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qx.Hosting</RootNamespace>
    <AssemblyName>QX.Hosting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QX.ClientCatalog\QX.ClientCatalog.csproj" />
    <ProjectReference Include="..\QX.Core\QX.Core.csproj" />
    <ProjectReference Include="..\QX.Game\QX.Game.csproj" />
    <ProjectReference Include="..\QX.Interception\QX.Interception.csproj" />
    <ProjectReference Include="..\QX.Mcp\QX.Mcp.csproj" />
    <ProjectReference Include="..\QX.Model\QX.Model.csproj" />
    <ProjectReference Include="..\QX.Protocol\QX.Protocol.csproj" />
    <ProjectReference Include="..\QX.Scripting\QX.Scripting.csproj" />
  </ItemGroup>

</Project>
